
name:                roboservant
version:             0.1.0.4
github:              "mwotton/roboservant"
license:             BSD3
copyright:           "2020 Mark Wotton, Samuel Schlesinger"
maintainer:          "mwotton@gmail.com"
synopsis:            Automatic session-aware servant testing
category:            Web
description:         Please see the README on GitHub at <https://github.com/mwotton/roboservant#readme>

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 4.22

- bytestring >= 0.11 && < 0.13
- containers >= 0.6 && < 0.9
- random >= 1.2 && < 1.4
- hashable >= 1.4 && < 1.6
- http-types >= 0.12 && < 0.13
- lifted-base >= 0.2 && < 0.3
- monad-control >= 1.0 && < 1.1
- mtl >= 2.2 && < 2.4
- minithesis >= 0.1 && < 0.2
- servant >= 0.18 && < 0.21
- servant-client >= 0.18 && < 0.21
- servant-flatten >= 0.2 && < 0.3
- servant-server >= 0.18 && < 0.21
- string-conversions >= 0.4 && < 0.5
- vinyl >= 0.13 && < 0.15
- dependent-sum >= 0.7 && < 0.8
- dependent-map >= 0.4 && < 0.5
- unordered-containers >= 0.2.10 && < 0.3
- text >= 1.2 && < 2.3
- time >= 1.9 && < 1.16

ghc-options:
- -Wall
- -fwrite-ide-info
- -hiedir=.hie
library:
  source-dirs: src

tests:
  roboservant-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - roboservant
    - aeson >= 1.5 && < 2.3
    - http-api-data >= 0.4 && < 0.7
    - http-client >= 0.5 && < 0.8
    - network >= 3.1 && < 3.3
    - sydtest >= 0.15 && < 0.22
    - wai >= 3.2 && < 3.3
    - warp >= 3.3 && < 3.5
  example:
    main: Example.lhs
    source-dirs: .

    dependencies:
      - roboservant
      - sydtest >= 0.15 && < 0.22
      - warp >= 3.3 && < 3.5
      - http-client >= 0.5 && < 0.8
      - aeson >= 1.5 && < 2.3
    ghc-options:    -pgmL markdown-unlit

    build-tools:  markdown-unlit
