
name:                roboservant
version:             0.1.0.4
github:              "mwotton/roboservant"
license:             BSD3
copyright:           "2020 Mark Wotton, Samuel Schlesinger"
synopsis:            Automatic session-aware servant testing
category:            Web
description:         Please see the README on GitHub at <https://github.com/mwotton/roboservant#readme>

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5

- bytestring
- containers
- random
- hashable
- http-types
- lifted-base
- monad-control
- mtl
- servant # >= 0.17
- servant-client # >= 0.17
- servant-flatten
- servant-server # >= 0.17
- string-conversions
- vinyl
- dependent-sum
- dependent-map
- unordered-containers
- text
- time

ghc-options:
- -Wall
- -fwrite-ide-info
- -hiedir=.hie
library:
  source-dirs: src

tests:
  roboservant-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - roboservant
    - aeson
    - hspec
    - hspec-core
    - http-api-data
    - http-client
    - hspec-wai
    - wai
    - warp
  example:
    main: Example.lhs
    source-dirs: .

    dependencies:
      - roboservant
      - hspec
      - warp
      - http-client
      - aeson
      - hspec-core
    ghc-options:    -pgmL markdown-unlit

    build-tools:  markdown-unlit
