# nb: 16.8 doesn't work because the version of servant is too old to have FoldLenient', fixme.
resolver: lts-16.16
packages:
- .

extra-deps:
- servant-flatten-0.2@sha256:276896f7c5cdec5b8f8493f6205fded0cc602d050b58fdb09a6d7c85c3bb0837,1234
- vinyl-0.13.0
- dependent-sum-0.7.1.0
- constraints-extras-0.3.0.2
- dependent-map-0.4.0.0

- servant-0.18.2
- servant-client-0.18.2
- servant-client-core-0.18.2
- servant-server-0.18.2
