# modified from https://github.com/jgm/pandoc/blob/master/.github/workflows/ci.yml
name: Cabal CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        versions:
          - ghc: '9.8.2'
            cabal: '3.10.2.0'
          - ghc: '9.6.5'
            cabal: '3.10.2.0'
          - ghc: '9.4.8'
            cabal: '3.10.2.0'
    steps:
      - uses: actions/checkout@v4

      - name: Install cabal & ghc
        uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.versions.ghc }}
          cabal-version: ${{ matrix.versions.cabal }}

      - name: Cache cabal global package db
        id: cabal-global
        uses: actions/cache@v4
        with:
          path: |
            ~/.cabal
          key: ${{ runner.os }}-${{ matrix.versions.ghc }}-${{ matrix.versions.cabal }}-cabal-global-${{ hashFiles('cabal.project') }}

      - name: Cache cabal build
        id: cabal-local
        uses: actions/cache@v4
        with:
          path: |
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.versions.ghc }}-${{ matrix.versions.cabal }}-cabal-local

      - name: Install dependencies
        run: |
          cabal update
          cabal build all --dependencies-only --enable-tests --disable-optimization

      - name: Build
        run: |
          cabal build all --enable-tests --disable-optimization 2>&1 | tee build.log

      - name: Test
        run: |
          cabal test all --disable-optimization
