name: Stack CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  stack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Haskell Stack
        uses: haskell-actions/setup@v2
        with:
          enable-stack: true
          stack-version: '3.7.1'

      - name: Cache ~/.stack
        uses: actions/cache@v4
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml') }}

      - name: Test
        run: stack test
